[project]
name = "helloworld_python_achieveravi"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "achieveravi", email = "ravi.achieve@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
helloworld-python = "helloworld_python:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
