# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    environment:
      name: pypi
      url: https://pypi.org/achieveravi/helloworld-python

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up uv and Python
      uses: astral-sh/setup-uv@v10.0.1
      with:
        version: "latest"
        python-version: "3.12" # Matches your pyproject.toml requirement

    - name: Build source and wheel distributions
      run: uv build
